[package]
name = "rgeometry-playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.62"
eframe = "0.19.0"
rand = "0.8.5"
rgeometry = { path = "../rgeometry" }
stopwatch = "0.0.7"
