[package]
name = "asm"
version = "0.1.0"
authors = ["Jihyun Yu <yjh0502@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.74"
js-sys = "0.3.59"
rgeometry = { path = "../../rgeometry" }
core = { path = "../core" }
